### ISSUE TITLE
Save inference images

### ISSUE THREAD

**Issue by xiaofeng-c** [DonkeyShot21/UNO#3]
If i want to save the inference images to the folder given,waht should i do?

**Comment by DonkeyShot21** [comment]
Hi, if you want to save the images during training you can just get the images in the `validation_step`. Otherwise, if you just want to do inference with a pretrained model you can just load the model and do `test()`, see [PyTorchLightning docs](https://pytorch-lightning.readthedocs.io/en/latest/common/test_set.html)

**Comment by xiaofeng-c** [comment]
OK,i get it,thank you!
